# airflow.docker-compose.yaml

# declare a dict of services
services:

  # Airflow service
  airflow:

    # Container name of thes service
    container_name: "airflow_service"

    # base image
    # image: apache/airflow:latest
    # Build the custom image
    build:
      context: .
      dockerfile: airflow.Dockerfile

    # Always restart the container if it stops.
    # If it's manually stopped, it's restarted
    # only when Docker daemon restarts or the container itself is manually restarted.
    restart: always

    # Env variables to be used inside the container
    environment:

      # The home directory of Airflow inside the container
      AIRFLOW_HOME : /project/services/airflow

      # The directories of source code and scripts in the project
      # These locations will be added to let airflow see our files
      PYTHONPATH : /project/src:/project/scripts

      # A custom environment variable to our project directory
      PROJECTPATH: /project

    # Allows to create volumes
    volumes:

      # Creates a volume for airflow metadata
      - ./services/airflow:/opt/airflow

      # Creates a volume to store the project in the container
      - .:/project

    ports:
      # Used to map ports from host to guest (container)
      - 8080:8080

    # Command to run when we start the container
    # We do not need this since we have it in airflow.Dockerfile
    # command: airflow standalone