model_name: CatBoost
artifact_path: catboost

tag_key: "model"
tag_value: "yandex catboost"

module_name: "catboost"
class_name: "CatBoostRegressor"

params:
  iterations: [100, 500, 1000]
  bagging_temperature: [0, 0.3, 0.7, 1]
  depth: [2, 3, 5]
  logging_level: ['Silent']
  task_type: ['CPU'] # GPU 

