defaults:
  - _self_

folds: 3

evaluation_metric: "r2"
cv_evaluation_metric: "mean_test_r2"

pyfunc_predict_fn: "predict"

metrics:
  r2: "r2"
  mae: "neg_mean_absolute_error"
  rmse: "neg_root_mean_squared_error"