defaults:
  - _self_

folds: 3

pyfunc_predict_fn: "predict"

metrics_module: "sklearn.metrics"
metrics:
  r2: "r2_score"
  mae: "mean_absolute_error"
  rmse: "root_mean_squared_error"

evaluation_metric: "r2"
cv_evaluation_metric: "mean_test_r2"


