model_name: XGBoost
artifact_path: xgboost

tag_key: "model"
tag_value: "xgboost"

module_name: "xgboost"
class_name: "XGBRegressor"

params:
  gamma: [0, 0.5, 1, 5]
  max_depth: [4, 8, 12]
  subsample: [0.3, 0.6, 1]
  device: ["cuda:0"]

