defaults:
  - _self_
  - experiment
  - model/model

test: True

num_samples: 5
index: 1
test_data_version: 2
sample_path: "data/samples/sample.csv"
dvc_file_path: "data/samples.dvc"

dataset:
  url: "zameen-updated.csv"
  name: "zameen-updated"

data: 
  target_cols: ["price"]
  cat_cols: ["city", "location", "type", "purpose", "title"]

model:
  best_model_name: "Lasso"
  best_model_version: 69
  best_model_alias: "Lasso"



hydra:
  mode: MULTIRUN
  sweeper:
    params:
      +model: "lasso, knn" 

