defaults:
  - _self_
  - experiment
  - model/model

num_samples: 5
index: 2
sample_path: "data/samples/sample.csv"
dvc_file_path: "data/samples.dvc"

dataset:
  url: "zameen-updated.csv"
  name: "zameen-updated"

data: 
  target_cols: ["price"]

test: False

hydra:
  mode: MULTIRUN
  sweeper:
    params:
      +model: "xgboost, rfr, lasso, catboost" # xgboost, rfr, lasso, catboost