defaults:
  - _self_
  - experiment
  - model/model

num_samples: 5
index: 2
sample_path: "data/samples/sample.csv"
dvc_file_path: "data/samples.dvc"

dataset:
  url: "zameen-updated.csv"
  name: "zameen-updated"

data:
  target_cols: [ "price" ]

test: False

model:
  best_model_name: "XGBoost"
  best_model_version: 102
  best_model_alias: "champion"
  model_tag_key: "source"
  model_tag_value: "best_Grid_search_model"

hydra:
  mode: MULTIRUN
  sweeper:
    params:
      +model: "xgboost, lasso, catboost" # xgboost, rfr, lasso, catboost
      