defaults:
  - _self_
  - experiment
  - model/model

num_samples: 5
index: 1
sample_path: "data/samples/sample.csv"
dvc_file_path: "data/samples.dvc"

dataset:
  url: "zameen-updated.csv"
  name: "zameen-updated"

data:
  target_cols: [ "price" ]

test: False

model:
  best_model_name: "XGBoost"
  best_model_version: 48
  best_model_alias: "XGBoost"

hydra:
  mode: MULTIRUN
  sweeper:
    params:
      +model: "xgboost" # xgboost, rfr, lasso, catboost

deploy:
  model_port: 5000