defaults:
  - _self_
  - experiment
  - model/model

num_samples: 5

dataset:
  url: "zameen-updated.csv"
  name: "zameen-updated"

data: 
  target_cols: ["price"]

index: 1

test: False

hydra:
  mode: MULTIRUN
  sweeper:
    params:
      +model: "lasso" # xgboost, rfr, lasso, catboost