# .github/workflows/test-code.yaml

name: Test code

on:
  push:
    branches:
      - main
      - dev
    paths:
      - 'src/**'
      - 'scripts/**'
      - 'services/airflow/dags/**'
      - 'tests/**'
      - 'configs/**'
      - '.github/**'
  schedule:
    - cron: '*/5 * * * *'

permissions:
  contents: read

env:
  message: "Testing code!"

jobs:
  test-code:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: .

    steps:
      - name: Checking out our code
        uses: actions/checkout@v4
    
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.0'
          cache: 'pip'

      - name: Install Python packages
        run: |
          python3.11 -m pip install --upgrade pip 
          pip3.11 install -r requirements.txt 
      
      - name: Configure DVC remote with service account
        run: |
          echo "${{ secrets.GDRIVE_CREDENTIALS_DATA }}" > gdrive-credentials.json
          dvc remote modify myremote gdrive_use_service_account true
          dvc remote modify myremote --local gdrive_service_account_json_file_path gdrive-credentials.json

      - name: Check dvc config
        run: dvc status
        env:
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}

      - name: Pull DVC data
        run: dvc pull
        env:
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}

      - name: Run your app
        run: python3.11 src/app.py &

      - name: Export variables
        run: | 
          echo $PWD
          export ZENML_CONFIG_PATH=$PWD/services/zenml
          export PROJECTPATH=$PWD
          export AIRFLOW_HOME=$PWD/services/airflow
          export PYTHONPATH=$PWD/src

      - name: Run ZenML server
        run: zenml down && zenml up

      - name: Download Kaggle dataset
        run: python3.11 src/download_kaggle_dataset.py

      - name: Run tests and collect coverage
        run: |
          coverage run -m pytest tests
          coverage report
        env:
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}

      - name: Generate coverage badge
        run: |
          coverage-badge -o coverage.svg -f

      - name: Upload coverage badge
        uses: actions/upload-artifact@v3
        with:
          name: coverage-badge
          path: coverage.svg

  print_info:
    runs-on: ubuntu-latest
    needs: test-code
    steps:
      - name: Print my password
        run: | 
          # echo My password is ${{ secrets.PASSWORD }}
          echo My name is '${{ vars.NAME }}'

      - name: Print message
        run: echo $message
